# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Loggo < Formula
  desc "Rich Terminal User Interface for JSON logs"
  homepage "https://github.com/aurc/homebrew-loggo"
  version "0.2.14"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/aurc/loggo/releases/download/v0.2.14/loggo_0.2.14_darwin_arm64.tar.gz"
      sha256 "9e8ec87d7f589e174d76faf340f1d0963ec99af6a1a44332de13b0aef1ed8e76"

      def install
        bin.install "loggo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/aurc/loggo/releases/download/v0.2.14/loggo_0.2.14_darwin_amd64.tar.gz"
      sha256 "5f37b689c7581ad60d15771164dd585873a3c92e3b358404ba49af17f0e88f4e"

      def install
        bin.install "loggo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/aurc/loggo/releases/download/v0.2.14/loggo_0.2.14_linux_amd64.tar.gz"
      sha256 "01856679bed8e4f4c06ca49dcd4bc3240cd33be7d1a256152bdfa93497273f54"

      def install
        bin.install "loggo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aurc/loggo/releases/download/v0.2.14/loggo_0.2.14_linux_arm64.tar.gz"
      sha256 "1f45f7fc37bc210857907f1712952877c80d07b31bbafbdd45530f6f8488a7ae"

      def install
        bin.install "loggo"
      end
    end
  end

  def caveats; <<~EOS
    How to use this binary
  EOS
  end
end
